version: 0.0
os: linux
files:
  - source: /
    destination: /tmp/erp/
    overwrite: true
file_exists_behavior: OVERWRITE

hooks:
  AfterInstall:
    - location: etc/scripts/sync.sh
      timeout: 600
      